# LiteLLM Configuration for ai-servicers.com
# Updated with latest 2025 models: GPT-5, Claude Opus 4.1, Gemini 2.5

model_list:
  # --- OpenAI Models ---
  - model_name: gpt-5
    litellm_params:
      model: gpt-5  # GPT-5 base model
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-5-mini
    litellm_params:
      model: gpt-5-mini  # Smaller, faster GPT-5
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-5-nano
    litellm_params:
      model: gpt-5-nano  # Smallest, fastest GPT-5
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-5-chat-latest
    litellm_params:
      model: gpt-5-chat-latest  # GPT-5 Chat alias
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-4.1
    litellm_params:
      model: gpt-4.1  # GPT-4.1
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-4o
    litellm_params:
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  # --- Anthropic Claude Models ---
  - model_name: claude-opus-4.1
    litellm_params:
      model: claude-opus-4-1  # Claude Opus 4.1 (generic, no date)
      api_key: os.environ/ANTHROPIC_API_KEY
      
  - model_name: claude-opus-4
    litellm_params:
      model: claude-opus-4-0  # Claude Opus 4 (generic, no date)
      api_key: os.environ/ANTHROPIC_API_KEY
      
  - model_name: claude-thinking
    litellm_params:
      model: claude-opus-4-1  # Claude Opus 4.1 with extended thinking (generic)
      api_key: os.environ/ANTHROPIC_API_KEY
      
  - model_name: claude-sonnet-4
    litellm_params:
      model: claude-3-5-sonnet-20241022  # Claude 3.5 Sonnet (latest available)
      api_key: os.environ/ANTHROPIC_API_KEY

  # --- Google Gemini Models ---
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro  # Gemini 2.5 Pro
      api_key: os.environ/GEMINI_API_KEY
      
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash  # Gemini 2.5 Flash
      api_key: os.environ/GEMINI_API_KEY
      
  - model_name: gemini-2.5-flash-lite
    litellm_params:
      model: gemini/gemini-2.5-flash-lite  # Gemini 2.5 Flash-Lite
      api_key: os.environ/GEMINI_API_KEY
      
  - model_name: gemini-2.5-flash-image-preview
    litellm_params:
      model: gemini/gemini-2.5-flash-image-preview  # Gemini 2.5 Flash Image Preview
      api_key: os.environ/GEMINI_API_KEY
      
  - model_name: gemini-2.5-flash-preview-tts
    litellm_params:
      model: gemini/gemini-2.5-flash-preview-tts  # Gemini 2.5 TTS Flash
      api_key: os.environ/GEMINI_API_KEY
      
  - model_name: gemini-2.5-pro-preview-tts
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-tts  # Gemini 2.5 TTS Pro
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  drop_params: true          # Strip unsupported params per provider
  num_retries: 3             # Retry failed requests
  request_timeout: 300       # Timeout in seconds
  # No fallbacks configured per user request

router_settings:
  routing_strategy: "simple-shuffle"  # Changed from least-busy to simple-shuffle

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY    # Admin key for all operations
  database_url: os.environ/DATABASE_URL        # PostgreSQL for tracking
  database_type: "postgres"
  database_connection_pool_size: 10
  
  # Admin UI settings
  ui_username: os.environ/UI_USERNAME
  ui_password: os.environ/UI_PASSWORD
  ui_access_mode: "admin"
  
  # CORS settings for web access
  cors_allowed_origins: ["https://litellm.ai-servicers.com", "https://open-webui.ai-servicers.com"]
  
  # Logging
  json_logs: true
  log_level: "INFO"
  
  # Disable telemetry
  telemetry: false